version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: loyalty_postgres
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: loyalty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: loyalty_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  metabase:
    image: metabase/metabase
    container_name: loyalty_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: loyalty
      MB_DB_PORT: 5432
      MB_DB_USER: demo
      MB_DB_PASS: demo
      MB_DB_HOST: postgres
    depends_on:
      - postgres

  prefect:
    image: prefecthq/prefect:2-latest
    container_name: loyalty_prefect
    command: prefect server start
    ports:
      - "4200:4200"
    depends_on:
      - postgres

volumes:
  postgres_data:
